# Generated by Django 5.1.3 on 2024-12-17 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummarizerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingtime',
            name='UID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='SummarizerApp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordingtime',
            name='title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('SID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('transcription', models.TextField()),
                ('summary', models.TextField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='SummarizerApp.user')),
            ],
        ),
    ]
