# Generated by Django 5.1.3 on 2024-12-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummarizerApp', '0002_recordingtime_uid_recordingtime_title_user_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingtime',
            name='UID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='SummarizerApp.user'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='UID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='SummarizerApp.user'),
        ),
    ]
