# Generated by Django 5.1.3 on 2025-01-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummarizerApp', '0003_alter_recordingtime_uid_alter_summary_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingtime',
            name='window_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
